name: "PR Checks"
on: [push, pull_request]

jobs:
    test:
        runs-on: ubuntu-latest
        name: Action Test
        steps:
            - uses: actions/checkout@v1

            - uses: ./
              with:
                username: ${{ secrets.SAUCE_USERNAME }}
                accessKey: ${{ secrets.SAUCE_ACCESS_KEY }}
                url: https://www.saucedemo.com/
                # expected number of vulnerabilities
                allowedMediumVulnerabilties: 10
                allowedLowVulnerabilties: 14
                allowedInformationalVulnerabilties: 20
                # download all assets
                downloadReports: true
                downloadJobAssets: true

            # attach all reports and assets to the job
            - uses: actions/upload-artifact@v2
              with:
                name: reports
                path: ${{ steps.sauce-security-test.outputs.reports-folder-path }}
            - uses: actions/upload-artifact@v2
              with:
                name: assets
                path: ${{ steps.sauce-security-test.outputs.assets-folder-path }}
